export default types = {
  RECEIVE_STANDARD_ERROR: 'RECEIVE_STANDARD_ERROR',
  REQUEST_COURSES: 'REQUEST_COURSES',
  RECEIVE_COURSES_SUCCESS: 'RECEIVE_COURSES_SUCCESS',
  REQUEST_TEACHER: 'REQUEST_TEACHER',
  RECEIVE_TEACHER_SUCCESS: 'RECEIVE_TEACHER_SUCCESS',
  REQUEST_STUDENTS: 'REQUEST_STUDENTS',
  RECEIVE_STUDENTS_SUCCESS: 'RECEIVE_STUDENTS_SUCCESS',
  REQUEST_ATTENDANCES: 'REQUEST_ATTENDANCES',
  RECEIVE_ATTENDANCES_SUCCESS: 'RECEIVE_ATTENDANCES_SUCCESS',
  LOGOUT: 'LOGOUT',
}
