export default types = {
  RECEIVE_STANDARD_ERROR: 'RECEIVE_STANDARD_ERROR',
  REQUEST_COURSES: 'REQUEST_COURSES',
  RECEIVE_COURSES_SUCCESS: 'RECEIVE_COURSES_SUCCESS',
  REQUEST_TEACHER: 'REQUEST_TEACHER',
  RECEIVE_TEACHER_SUCCESS: 'RECEIVE_TEACHER_SUCCESS',
  LOGOUT: 'LOGOUT',
}
